version: "3"

services:
  mirror:
    image: verdaccio/verdaccio:4.3.4
    restart: always
    ports:
      - "4873:4873"
    volumes:
        - "./registry/storage:/verdaccio/storage"
        - "./registry/conf:/verdaccio/conf"
        - "./registry/conf/.htpasswd:/verdaccio/conf/htpasswd"
        - "./registry/logo.png:/logo.png"
    networks:
      # "internet" to be accessible from the host
      # but host can have no internet access.
      internet: {}
      # For "test" to be able to reach this container.
      noinet: {}

  test:
    depends_on:
      - mirror
    build:
      context: ./tester
    networks:
      noinet: {}

  download:
    depends_on:
      - mirror
    build:
      context: ./downloader
    volumes:
      - "./packages:/packages"
      - "./package.json:/package.json"
      - "./downloader/downloader.py:/downloader.py"
    networks:
      # Internet required here on the host.
      internet: {}

  push:
    depends_on:
      - mirror
    build:
      context: ./pusher
    volumes:
      - "./packages:/packages"
      - "./package.json:/package.json"
      - "./pusher/pusher.py:/pusher.py"
    networks:
      noinet: {}

# To make sure 'client' is offline
networks:
  internet:
    driver: bridge
  noinet:
    internal: true
