version: "3.2"

services:
  registry:
    privileged: true
    build: .
    restart: always
    ports:
      - "4873:4873"
    volumes:
      - "registry_storage:/verdaccio/storage"
      - "./registry/conf:/verdaccio/conf"
      - type: bind
        source: ./registry/conf/htpasswd
        target: /verdaccio/conf/htpasswd
      - type: bind
        source: ./registry/logo.png
        target: /logo.png
    networks:
      # "internet" to be accessible from the host
      # but host can have no internet access.
      internet: {}
      # For "test" to be able to reach this container.
      noinet: {}

  test:
    depends_on:
      - registry
    build:
      context: ./tester
    volumes:
      - "./package.json:/workdir/package.json"
    networks:
      noinet: {}

  download:
    build:
      context: ./downloader
    volumes:
      - "./packages:/packages"
      - "./package.json:/package.json"
      - "./downloader/downloader.py:/downloader.py"
    networks:
      # Internet required here on the host.
      internet: {}

  push:
    environment:
      REGISTRY_ENDPOINT: http://registry:4873
    build:
      context: ./pusher
    volumes:
      - "./packages:/packages"
      - "./package.json:/package.json"
      - "./pusher/pusher.py:/pusher.py"
    networks:
      noinet: {}

# To make sure 'client' is offline
networks:
  internet:
    driver: bridge
  noinet:
    internal: true

volumes:
  registry_storage:
