version: 2

jobs:

  build:
    docker:
      - image: docker:dind
    steps:
      - checkout
      - run: apk update
      - run: apk upgrade
      - run: apk add python python-dev py-pip build-base
      - run: curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
      - run: chmod +x /usr/local/bin/docker-compose
      - run: pip install docker-compose
      - run: docker-compose up --build mirror

  test:
    docker:
      - image: docker:dind
    steps:
      - checkout
      - run: apk add --no-cache curl
      - run: curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
      - run: chmod +x /usr/local/bin/docker-compose
      - run: docker-compose up download

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
