version: 2

jobs:

  build:
    docker:
      - image: jonaskello/docker-and-compose
    steps:
      - checkout
      - run: dockerd
      - run: docker-compose up --build mirror
 
  test:
    docker:
      - image: jonaskello/docker-and-compose
    steps:
      - checkout
      - run: dockerd
      - run: docker-compose up download

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
